server:
    port: 8888
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                default-label: main
                git: 
                    uri: http://github.com/berna-ozgen/microservice-config-server
    profiles:
        active: dev
